import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Jongseong KIM</title>
        <meta name="Brief " content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* Main Title section */}
        <h1 className={styles.title}>
          This is <a href="https://nextjs.org">Jongseong!</a>
        </h1>
    
        <p className={styles.description}>
          I am Jongseong KIM{' '}
          <code className={styles.code}>김 종성(金 鐘城)</code>
        </p>

        {/* Body Section */}
        <div className={styles.grid}>
          {/* Top Left Section */}
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Name &rarr;</h2>
            <p>My Name and several information is from here.</p>
          </a>

          {/* Top Right Section */}
          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Blog &rarr;</h2>
            <p>You can acess my blog site and so on.</p>
          </a>

          {/* Bottom Left Section */}
          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Interest &rarr;</h2>
            <p>I am interested in ... <br />In this section, you can glance at my hobby.</p>
          </a>

          {/* Bottom Righ Section */}
          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Tools &rarr;</h2>
            <p>
              I have used these tools... <br />
              It means I can handle these skills...
            </p>
          </a>
        </div>
      </main>

      {/* Page Footer section */}
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
